default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: root
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  role: administrator
  host: localhost

development:
  <<: *default
  database: blogpost_development

test:
  <<: *default
  database: blogposttest

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: blogpost_prod
  username: rishi_user_techquie
  password: <%= ENV['NOT_SURE_DB_PASSWORD'] %>
